# docker-compose.yaml
version: '3'
services:
  node_app:
    image: node:lts-bookworm-slim  # NodeJS v18 on Debian GNU/Linux 12 (bookworm)
    command: bash -c '
      cat /etc/os-release &&
      node -v &&
      npm -v &&
      npm install -g date-fns @azure/msal-node --verbose 2>&1 &&
      node aztoken.js'
    volumes:
      - ./:/app
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
      - MAZ_CLIENT_ID=${MAZ_CLIENT_ID}
      - MAZ_CLIENT_SECRET=${MAZ_CLIENT_SECRET}
      - MAZ_TENANT_ID=${MAZ_TENANT_ID}
    working_dir: /app

# BUILD & RUN: docker compose up --build
# JUST RUN   : docker compose up
# INSPECT    : docker compose run --build node_app sh

