#!/bin/bash
# build
# Make the binary and place in the PATH
set -euo pipefail  # Fail on any error
PRG=zman
case "$OSTYPE" in
    "linux-gnu"* ) printf "==> OS = Linux\n" && BIN=$GOPATH/bin/${PRG} ;;
    "darwin"* )    printf "==> OS = macOS\n" && BIN=$GOPATH/bin/${PRG} ;;
    "msys"* )      printf "==> OS = Windows with GitBASH\n" && BIN=$GOPATH/bin/${PRG}.exe ;;
    * )            printf "==> OS = \"$OSTYPE\", unknown! (Options are Linux, macOS, or Windows with GitBASH)\n" && exit 1 ;;
esac
go fmt
go mod tidy
go test ./...
go build -ldflags "-s -w" -o $BIN
ls -l $GOPATH/bin/$PRG

printf "\n==> Version in main.go:\n"
grep "prgver.*=" main.go
printf "\n==> HEAD of go.mod:\n"
head go.mod

printf "\n==> Last 3 tag versions = "
git tag | tail -3 | tr '\n' ' '
CurrentTag=`git tag | tail -1`
Prg=`head -1 go.mod | awk -F'/' '{print $NF}' | awk '{print $NF}'`
printf "\n\n==> To publish, do below one-liner, updating tag version and comments accordingly:\n\n"
printf "Tag=$CurrentTag && Prg=$Prg && git add . && git commit -m \"\$Tag: updates\" && git tag \$Tag && git push origin \$Tag && git push\n\n"

exit 0
