#!/bin/bash
# build
# Make the binary and place in the PATH
set -euo pipefail  # Fail on any error
PRG=zls
case "$OSTYPE" in
    "linux-gnu"* ) echo "=> OS = Linux" && BIN=$GOPATH/bin/${PRG} ;;
    "darwin"* )    echo "=> OS = macOS" && BIN=$GOPATH/bin/${PRG} ;;
    "msys"* )      echo "=> OS = Windows with GitBASH" && BIN=$GOPATH/bin/${PRG}.exe ;;
    * )            printf "=> OS = \"$OSTYPE\", unknown! (Options are Linux, macOS, or Windows with GitBASH)\n" && exit 1 ;;
esac
go mod tidy
go test ./...
go build -ldflags "-s -w" -o $BIN
ls -l $GOPATH/bin/$PRG
exit 0
