#!/bin/bash
# pman
# Azure REST API caller

PRGNAME="pman"
PRGVER="1.0.1"
set -euo pipefail

check_binary() {
    if [[ -z "$(which $1 2>/dev/null)" ]]; then
        printf "Missing '$1' binary!\n" && exit 1 
    fi
}
for B in zls curl ; do check_binary $B ; done

print_usage() {
    printf "$PRGNAME Azure REST API Caller v$PRGVER\n"
    printf "  Usage Examples:\n"
    printf "    $PRGNAME GET \"https://graph.microsoft.com/v1.0/me\"\n"
    printf "    $PRGNAME GET \"https://management.azure.com/subscriptions?api-version=2022-12-01\" [other curl options]\n"
    printf "    $PRGNAME GET \"https://graph.microsoft.com/v1.0/applications/3eec32f4-6ca1-4d1d-9335-19518aa196c4\" [other curl options]\n"
    exit 1
}

[[ $# -eq 0 || $# -lt 2 ]] && print_usage && exit 1

METHOD="$1"
URL="$2"
OPTIONAL_ARGS="${@:3}"

if [[ $URL == *"https://graph.microsoft.com"* ]]; then
    TK=$(zls -tmg)
elif [[ $URL == *"https://management.azure.com"* ]]; then
    TK=$(zls -taz)
else
    print_usage && exit 1
fi

#set -x
curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $TK" -X $METHOD "$URL" $OPTIONAL_ARGS
#set +x

exit 0

