#!/bin/bash
# pman
# Azure REST API caller

PRGVER="1.0.0"
set -euo pipefail

[[ -z "$(which zls)" ]] && printf "Missing 'zls' binary\n" && exit 1
[[ -z "$(which curl)" ]] && printf "Missing 'curl' binary\n" && exit 1

function print_usage {
    printf "$(basename $0) Azure REST API Caller v$PRGVER\n"
    printf "  Usage Examples:\n"
    printf "    $(basename $0) GET \"https://graph.microsoft.com/v1.0/applications/3eec32f4-6ca1-4d1d-9335-19518aa196c4\" [other curl options]\n"
    printf "    $(basename $0) GET \"https://management.azure.com/providers/Microsoft.Authorization/roleDefinitions?api-version=2022-04-01\" [other curl options]\n"
    exit 1
}

[[ $# -eq 0 ]] && print_usage && exit 1

METHOD="$1"
URL="$2"
OPTIONAL_ARGS="${@:3}"

if [[ $URL == *"https://graph.microsoft.com"* ]]; then
    TK=$(zls -tmg)
elif [[ $URL == *"https://management.azure.com"* ]]; then
    TK=$(zls -taz)
else
    print_usage && exit 1
fi

#set -x
curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $TK" -X $METHOD "$URL" $OPTIONAL_ARGS
#set +x

exit 0

