# docker-compose-py.yaml

version: '3'
services:
  python_app:
    image: ubuntu:latest
    command: bash -c '
      apt update &&
      apt install -y python3 python3.10-venv &&
      export PIP_EXTRA_INDEX_URL=https://pypi.python.org/simple/ &&
      cd / &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install --upgrade pip &&
      pip install msal &&
      python /app/aztoken.py'
    volumes:
      - ./:/app
    environment:
      - MAZ_CLIENT_ID=${MAZ_CLIENT_ID}
      - MAZ_CLIENT_SECRET=${MAZ_CLIENT_SECRET}
      - MAZ_TENANT_ID=${MAZ_TENANT_ID}
    working_dir: /app

# BUILD & RUN: docker compose -f docker-compose-py.yaml up --build
# JUST RUN   : docker compose -f docker-compose-py.yaml up
# INSPECT    : docker compose -f docker-compose-py.yaml run --build node_app bash
